version: 2

sources:
  - name: zuerich_raw
    database: zuerich_db
    schema: raw
    tables:
      - name: shopping
      - name: activities
      - name: bars
      - name: culture
      - name: dining
      - name: hotels
      - name: museums
      - name: nightlife
      - name: sights
      - name: sport
      - name: wellness
